Avoid using custom version requirements
opensearch-project/opensearch-rs pull request #177
Opened 2023-09-01 02:59 UTC by rukai

Using custom version requirements in a library is generally considered a bad idea as it can lead to broken builds downstream.
The cargo docs [goes into this](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-requirements) in the box starting with:

> Recommendation: When in doubt, use the default version requirement operator.
> ...

In this PR I have removed all non-default version requirements.
Happy to discuss if you feel some are needed.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-01 04:40 UTC, Xtansia requested changes
Hi @rukai,

Appreciate the PR! I've just gone through and mostly for my own sake commented on the various changes about whether they remain equivalent etc. There's only one problematic change which is those for the `aws-*` crates where we want to "float up" to the version used by the consumer as `0.` versions behave differently with the default operator than `1.` (or greater) do.

ie.
`"1.53"` == `">= 1.53.0, < 2.0.0"`
`"0.53"` == `">= 0.53.0, < 0.54.0"`

2023-09-01 04:40 UTC, Xtansia commented on api_generator/Cargo.toml
> +globset = "0.4"
These are equivalent so 👍

2023-09-01 04:40 UTC, Xtansia commented on api_generator/Cargo.toml
> +quote = "1.0"
These widen from `1.0.*` to `1.*.*`, probably okay because semver, and also currently proc-macro2/quote hasn't hit `1.1` yet

2023-09-01 04:40 UTC, Xtansia commented on api_generator/Cargo.toml
> +reqwest = { version = "0.11", features = ["blocking"] }
These are equivalent so 👍

2023-09-01 04:40 UTC, Xtansia commented on api_generator/Cargo.toml
> +serde = { version = "1", features = ["derive"] }
These are equivalent so 👍

2023-09-01 04:40 UTC, Xtansia commented on api_generator/Cargo.toml
> +tar = "0.4"
* syn widens from `2.0.*` to `2.*.*`, should be okay due to semver and syn hasn't hit `2.1` yet
* tar remains equivalent

2023-09-01 04:40 UTC, Xtansia commented on opensearch/Cargo.toml
> +dyn-clone = "1"
These are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on opensearch/Cargo.toml
> +serde_with = "3"
These are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on opensearch/Cargo.toml
> +aws-types = { version = "0.53", optional = true }
This restricts aws-* to `0.53.*` which causes problems for users as the aws types are part of a public api, so if user has a differing version they end up being incompatible types. 👎

2023-09-01 04:40 UTC, Xtansia commented on opensearch/Cargo.toml
> +clap = "2"
* aws-config: See above about aws-* 👎 
* chrono & clap are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on opensearch/Cargo.toml
> +xml-rs = "0.8"
These are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on yaml_test_runner/Cargo.toml
> +clap = "2"
These are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on yaml_test_runner/Cargo.toml
> +quote = "1.0"
These widen from `1.0.*` to `1.*.*`, probably okay because semver, and also currently proc-macro2/quote hasn't hit `1.1` yet

2023-09-01 04:40 UTC, Xtansia commented on yaml_test_runner/Cargo.toml
> +serde_json = { version = "1", features = ["arbitrary_precision"] }
These are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on yaml_test_runner/Cargo.toml
> +globset = "0.4"
These are equivalent 👍

2023-09-01 04:40 UTC, Xtansia commented on yaml_test_runner/Cargo.toml
> +syn = { version = "1.0", features = ["full"] }
This widens from `1.0.*` to `1.*.*`, but syn never released a `1.1` so okay

2023-09-01 05:46 UTC, rukai commented
I've undone the aws changes since, as you've correctly identified that would be a breaking change.

That said specifying the AWS versions like that is quite dangerous because they can freely issue breaking changes within any 0.x.0 releases.
I dont have a good solution for you though since you cant issue a breaking release until opensearch itself does given this policy: https://docs.rs/opensearch/latest/opensearch/#versions-and-compatibility
But its also not really my concern as I dont enable the aws-auth feature anyway.

2023-09-03 22:53 UTC, Xtansia approved these changes

2023-09-03 23:09 UTC, Xtansia requested changes
@rukai Thanks for reverting the `aws-*` versioning, looks good now, just missing `--signoff` on your most recent commit, if you could amend that then that'd be great.

I'm aware that a breaking change could be introduced in any `0.x.0` version of `aws-*` however it is somewhat of a calculated risk for the time being as the parts we use are mostly stable, and the end user has control of what `aws-*` version is brought in and can roll-back or pin as a work around if a breakage did come. But I have been looking for mechanism to better encapsulate this dependency and the API usage of it, which if you have ideas or opinions on good ways to achieve that I'd love to hear your thoughts.

Additionally that version mandate about being lockstep with the server major versioning, is a relic of the fork from Elasticsearch and is not necessarily true for today so I've created an issue to update that.

2023-09-04 01:58 UTC, rukai commented
oops, sign off should be fixed now.

2023-09-04 03:17 UTC, Xtansia approved these changes

2023-09-04 03:30 UTC, merged