Use optional when id is optional in bulk requests
opensearch-project/opensearch-rs pull request #245
Opened 2024-04-03 06:40 UTC by camerondurham

### Description

*Potentially a controversial, breaking change*, happy to discuss further in the related issue if it's best to just add a new constructor.

#### Change

Changed types to `id: Option<S>` when `_id` is optional in the bulk request, otherwise, keep `id` parameter as `String`.

This change is making the Bulk operation constructor parameters more closely match the Bulk API, specifically when `_id` is required or not.

Summarized from the docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-bulk.html#bulk-api-request-body
- `create`: `_id` (optional, string)
- `delete`: `_id` (required, string)
- `index`: `_id` (optional, string)
- `update` `_id` (required, string)

### Issues Resolved

Related to, and may close issue #241 .

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-03 17:58 UTC, dblock commented
@Xtansia take a look?

Regarding a breaking change: if it can be avoided it's best. Then we don't need to do a major release and break users. You can deprecate the old method.

2024-04-03 21:06 UTC, Xtansia commented
I also don't feel this warrants a breaking version bump just for this, however there is an opportunity where you could PR a non-breaking change directly into `2.x` and make the breaking change in `main`. Then it'll be usable sooner via a minor version, and the "corrected" version can just wait for whenever we cut a 3.0.0

2024-04-07 22:52 UTC, Xtansia requested changes
Changes look good, I just have some thoughts about the naming. 
Could you please also add an entry to the [CHANGELOG.md under the "Added" header](https://github.com/opensearch-project/opensearch-rs/blob/main/CHANGELOG.md#added).
You can ignore the `Link Checker` workflow failure.

2024-04-07 22:52 UTC, Xtansia commented on opensearch/src/root/bulk.rs
> +        BulkCreateOperation::new_no_id(source)
I'd prefer `without_id` over `no_id` for comprehensibility.
```suggestion
    /// Creates a new instance of [bulk create operation](BulkCreateOperation) without an explicit id
    pub fn create_without_id(source: B) -> BulkCreateOperation<B> {
        BulkCreateOperation::new_without_id(source)
```

2024-04-07 22:52 UTC, Xtansia commented on opensearch/src/root/bulk.rs
> +    pub fn new_no_id(source: B) -> Self {
I'd prefer `without_id` over `no_id` for comprehensibility.
```suggestion
    /// Creates a new instance of [BulkCreateOperation] without an explicit id
    pub fn new_without_id(source: B) -> Self {
```

2024-04-07 22:52 UTC, Xtansia commented on opensearch/src/root/bulk.rs
> +        ops.push(BulkOperation::create_no_id(CreateDoc { bar: "create" }))?;
```suggestion
        ops.push(BulkOperation::create_without_id(CreateDoc { bar: "create" }))?;
```

2024-04-08 01:19 UTC, camerondurham commented
Thanks for the review, I accepted all suggestions and added an entry to the changelog.

2024-04-08 03:05 UTC, Xtansia approved these changes

2024-04-08 04:09 UTC, reta approved these changes

2024-04-08 04:12 UTC, merged